name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        project: [core, client, server]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11.0.18
      - name: Ktlint check
        run: ./gradlew :${{ matrix.project }}:ktlintCheck
      - name: Compile
        run: ./gradlew :${{ matrix.project }}:compileKotlin
      - name: Test
        run: xvfb-run --auto-servernum ./gradlew :${{ matrix.project }}:test
